menu/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.ItemList_short.as_view(), name='home'),
    path('menu/', views.ItemList.as_view(), name='menu'),
    path('menu/<slug:slug>/', views.ItemDetail.as_view(), name='item_detail'),
    path('menu/like/<slug:slug>', views.ItemLike.as_view(), name='item_like'),
]

reservation/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.add_reservation,
         name='add_reservation'),
    path('view/', views.ReservationList.as_view(),
         name='view_reservation'),
    path('edit/<pk>', views.edit_reservation,
         name='edit_reservation'),
    path('delete/<pk>', views.delete_reservation,
         name='delete_reservation'),
]

rustytavern/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('menu.urls'), name='menu.urls'),
    path('accounts/', include('allauth.urls')),
    path('reservation/', include(
        'reservation.urls'), name='reservation.urls'),
]

menu/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, 'Draft')), ((1, 'Published'))


class Item(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='menu_items')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    food_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='menu_likes', blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def number_of_reviews(self):
        return self.reviews.filter(approved=True).count()


class Review(models.Model):
    item = models.ForeignKey(
        Item, on_delete=models.CASCADE, related_name='reviews')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Review {self.body} by {self.name}'

reservation/models.py
from django.db import models


class Reservation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()
    table_for = models.PositiveIntegerField(default=1)
    Date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return self.name

menu/forms.py
from .models import Review
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('body',)

reservation/forms.py
from .models import Reservation
from django import forms
from django.forms import DateInput
from django_flatpickr.widgets import DatePickerInput
import datetime

INTERVALS = [
    (datetime.time(hour=x, minute=y), '{:02d}:{:02d}'.format(x, y))
    for x in range(11, 21)
    for y in range(0, 60, 15)
]


class ReserveTableForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ('name', 'phone', 'table_for', 'Date', 'time')
        widgets = {
            'Date': DatePickerInput(),
            'time': forms.Select(choices=INTERVALS)
        }

menu/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import Item
from .forms import ReviewForm


class ItemList_short(generic.ListView):
    model = Item
    queryset = Item.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 3


class ItemList(generic.ListView):
    model = Item
    queryset = Item.objects.filter(status=1).order_by('-created_on')
    template_name = 'menu.html'
    paginate_by = 12


class ItemDetail(View):
    def get(self, request, slug, *args, **kwargs):
        queryset = Item.objects.filter(status=1)
        item = get_object_or_404(queryset, slug=slug)
        reviews = item.reviews.filter(approved=True).order_by('created_on')
        liked = False
        if item.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            'item_detail.html',
            {
                'item': item,
                'reviews': reviews,
                'reviewed': False,
                'liked': liked,
                'review_form': ReviewForm(),
            }
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Item.objects.filter(status=1)
        item = get_object_or_404(queryset, slug=slug)
        reviews = item.reviews.filter(approved=True).order_by('created_on')
        liked = False
        if item.likes.filter(id=self.request.user.id).exists():
            liked = True

        review_form = ReviewForm(data=request.POST)

        if review_form.is_valid():
            review_form.instance.email = request.user.email
            review_form.instance.name = request.user.username
            review_form.instance.item = item
            review_form.save()
        else:
            review_form = ReviewForm()

        return render(
            request,
            'item_detail.html',
            {
                'item': item,
                'reviews': reviews,
                'reviewed': True,
                'liked': liked,
                'review_form': review_form,
            },
        )


class ItemLike(View):
    def post(self, request, slug):
        item = get_object_or_404(Item, slug=slug)

        if item.likes.filter(id=request.user.id).exists():
            item.likes.remove(request.user)
        else:
            item.likes.add(request.user)

        return HttpResponseRedirect(reverse('item_detail', args=[slug]))

reservation/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, reverse
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.views import generic, View
from .models import Reservation
from .forms import ReserveTableForm


class ReservationList(generic.ListView):
    model = Reservation
    queryset = Reservation.objects.order_by('Date')
    template_name = 'view_reservation.html'


def add_reservation(request):
    form = ReserveTableForm()

    if request.method == 'POST':
        form = ReserveTableForm(request.POST)

        if form.is_valid():
            form.save()

            context = {
                'form': form,
                'reserved': True,
            }

    if request.method == 'GET':
        context = {
            'form': form,
            'reserved': False,
        }

    return render(request, 'add_reservation.html', context)


def edit_reservation(request, pk):
    reservation = get_object_or_404(Reservation, id=pk)
    form = ReserveTableForm(instance=reservation)
    if request.method == 'POST':
        form = ReserveTableForm(request.POST, instance=reservation)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('view_reservation'))

    if request.method == 'GET':
        context = {
                    'form': form
                }
    return render(request, 'edit_reservation.html', context)


def delete_reservation(request, pk):
    reservation = get_object_or_404(Reservation, id=pk)
    reservation.delete()
    return HttpResponseRedirect(reverse('view_reservation'))

templates/add_reservation.html
{% extends 'base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
{{ form.media }}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 mt-5">
            {% if reserved %}
            <div class="alert alert-light" role="alert">
                <p>Thank you {{ form.name.value }} for the Reservation, here are the details:</p>
                <ul class="list-unstyled text-secondary">
                    <li>Name: {{ form.name.value }}</li>
                    <li>Phone: {{ form.phone.value }}</li>
                    <li>Table for: {{ form.table_for.value }}</li>
                    <li>Date: {{ form.Date.value }}</li>
                    <li>Time: {{ form.time.value }}</li>
                </ul>
                <p>Make sure you keep take note of this information, otherwise you can just contact us and we will be
                    happy to help you out.</p>
                <a class="nav-link {% if '/' == request.path %}active{% endif %} text-center" href="{% url 'home' %}">
                    <button class="btn btn-success px-5">Return to Home page</button>
                </a>
            </div>
            {% else %}
            <form method="POST" class="color-white">
                {% csrf_token %}
                <h1 class="text-center color-main">Reservation</h1>
                {{ form|crispy }}
                <button type="submit" class="btn btn-success px-5">Submit</button>
            </form>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/b66a8a8811.js" crossorigin="anonymous"></script>

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IM+Fell+English+SC&family=Lato&display=swap" rel="stylesheet">

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

    <!-- Stylesheet link -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Rusty Tavern</title>
</head>

<body>
    <div class="overlay">
        <div class="background-img"></div>

        <!-- Navigation -->
        <nav class="navbar justify-content-center mt-5">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link {% if '/' == request.path %}active{% endif %}" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if '/menu/' == request.path %}active{% endif %}"
                        href="{% url 'menu' %}">Menu</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if '/reserve_table/' == request.path %}active{% endif %}"
                        href="{% url 'add_reservation' %}">Reservation</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if '/reserve_table/view_reservation' == request.path %}active{% endif %}"
                        href="{% url 'view_reservation' %}">View Reservations</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if '/accounts/logout/' == request.path %}active{% endif %}"
                        href="{% url 'account_logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link {% if '/accounts/signup/' == request.path %}active{% endif %}"
                        href="{% url 'account_signup' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if '/accounts/login/' == request.path %}active{% endif %}"
                        href="{% url 'account_login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>

        <!-- Main content -->
        <main>
            {% block content %}
            <!-- Our content will go here -->
            {% endblock %}
        </main>

    </div>

    <!-- Footer -->
    <footer>

    </footer>

    <!-- Java script -->
    <script src="{% static 'js/script.js' %}"></script>

    <!-- Bootstrap javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
    </div>
</body>

</html>

templates/card.html
{% block card %}
<div class="card h-100 d-flex mt-2-sm">
    <!-- Image place holder -->
    {% if 'placeholder' in item.food_image.url %}
    <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" alt="default image"
        class="card-img-top">
    {% else %}
    <img src="{{ item.food_image.url }}" alt="food image" class="card-img-top">
    {% endif %}
    <div class="card-body">
        <h4 class="card-title">{{ item.title }}</h4>
        <p class="card-text">{{ item.excerpt }}</p>
    </div>

    <div class="container inline-d-flex justify-content-end">
        <!-- Displaying created on and number of likes -->
        <p class="card-text text-muted h6 text-center">
            <i class="fa-solid fa-heart"></i> {{ item.number_of_likes }}
            <i class="fa-solid fa-comment"></i> {{ item.number_of_reviews }}
        </p>
        <div class="mb-2 text-center">
            <a href="{% url 'item_detail' item.slug %}" class="btn btn-success">More info / Review</a>
        </div>
    </div>
</div>
{% endblock %}

templates/edit_reservation.html
{% extends 'base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
{{ form.media }}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 mt-5">
            <h1 class="text-center color-main">Reservation</h1>
            <form method="POST" class="color-main">
                {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success px-5">Update Reservation</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}

<!-- Welcome text -->
<div class="container">
    <h5 class="text-center text-uppercase mt-5">Welcome to</h5>
    <h2 class="text-center text-uppercase">Rusty Tavern</h2>
    <p class="text-center mt-3 color-white">The place where you can find calm and relaxing music of old and rustic
        food!
    </p>
</div>

<!-- Cards -->
<div class="container">
    <div class="row justify-content-center">
        <!-- For loop for item_list -->
        {% for item in item_list %}
        <div class="col-md-4 mt-3">
            {% include 'card.html' %}
        </div>
        {% endfor %}
    </div>
    <!-- If more then 3 pages exists paginate them -->
    {% if is_paginated %}
    <div class="d-flex justify-content-center mt-4">
        <nav aria-label="Page navigation">
            <ul class="pagination">

                <!-- Goes back to the previous page -->
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">&laquo;
                        PREV
                    </a>
                </li>
                {% endif %}

                <!-- Goes forward to the next page -->
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary"> NEXT
                        &raquo;</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
    {% endif %}
</div>

{% endblock %}

templates/item_detail.html
{% extends 'base.html' %}
{% block content %}

{% load crispy_forms_tags %}

<h1 class="text-center color-main mt-5">Details</h1>

<div class="container mt-3">
    <div class="row gx-3 mb-3">
        <div class="col">
            <div class="p-3 card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-4">
                            <div class="col-md-4 img-thumbnail w-100">
                                <!-- Default image if none exists -->
                                {% if 'placeholder' in item.food_image.url %}
                                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg"
                                    alt="default image" class="card-img-top">
                                {% else %}
                                <img src="{{ item.food_image.url }}" alt="food image" class="card-img-top">
                                {% endif %}
                            </div>
                        </div>
                        <!-- Content -->
                        <div class="col">
                            <h1 class="post-title text-center">{{ item.title }}</h1>
                            <p class="col-md-6 card-text">
                                {{ item.content | safe }}
                            </p>
                            <!-- Number of likes -->
                            <div class="mt-5 text-center">
                                <strong>
                                    {% if user.is_authenticated %}
                                    <form class="d-inline" action="{% url 'item_like' item.slug %}" method="POST">
                                        {% csrf_token %}
                                        {% if liked %}
                                        <button class="btn" type="submit" value="{{ item.slug }}">
                                            <i class="fa-solid fa-heart text-danger"></i>
                                        </button>
                                        {% else %}
                                        <button class="btn" type="submit" value="{{ item.slug }}">
                                            <i class="fa-regular fa-heart"></i>
                                        </button>
                                        {% endif %}
                                    </form>
                                    {% else %}
                                    <span class="text-danger"><i class="fa-regular fa-heart"></i></span>
                                    {% endif %}
                                    <span class="text-secondary">{{ item.number_of_likes }}</span>
                                </strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row gx-3">
        <div class="col-8">
            <div class="p-3 card">
                <!-- Displays Reviews -->
                <h3>Reviews:</h3>
                <div class="card-body">
                    {% for review in reviews %}
                    <div class="reviews">
                        <p class="font-weight-bold">
                            {{ review.name }}
                            <span class="text-muted font-weight-normal">
                                {{ review.created_on }}
                            </span> Wrote:
                        </p>
                        {{ review.body | linebreaks }}
                    </div>                                        
                    {% empty %}
                    <p>There are no reviews yet, so if you have tried <strong>{{ item }}</strong>. Please consider to review it to help us
                        improve and for others to learn from your experiance.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col">
            <div class="p-3 card">
                <!-- Add reviews -->
                <div class="card-body">
                    {% if reviewed %}
                    <div class="alert alert-success" role="alert">
                        Your review is awaiting approval
                    </div>
                    {% else %}
                    {% if user.is_authenticated %}

                    <h3>Leave a Review:</h3>
                    <p>Posting as: {{ user.username }}</p>
                    <form method="post">
                        {{ review_form | crispy }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success btn-lg">Submit</button>
                    </form>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/menu.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center color-main mt-5">Menu</h1>

<div class="container mt-3">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Food</th>
                            <th>Description</th>
                            <th>Likes</th>
                            <th>Reviews</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in item_list %}
                        <tr class="align-middle">
                            <th scope="row">{{ item.title }}</th>
                            <td class="col-7">{{ item.excerpt }}</td>
                            <td>
                                <p class="card-text text-muted h6">
                                    <i class="fa-solid fa-heart"></i> {{ item.number_of_likes }}
                                </p>
                            </td>
                            <td>
                                <p class="card-text text-muted h6">
                                    <i class="fa-solid fa-comment"></i> {{ item.number_of_reviews }}
                                </p>
                            </td>
                            <td>
                                <a href="{% url 'item_detail' item.slug %}" class="btn btn-success">More info /
                                    Review</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% if is_paginated %}
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">

                        {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a>
                        </li>
                        {% endif %}

                        {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/reservation_table.html
<tr class="align-middle">
    <th scope="row">{{ reservation.Date}}</th>
    <td>{{ reservation.name }}</td>
    <td>{{ reservation.email }}</td>
    <td>{{ reservation.phone }}</td>
    <td>{{ reservation.table_for }}</td>
    <td>{{ reservation.Date }}</td>
    <td>{{ reservation.time }}</td>
    <td>
        <a href="../edit/{{ reservation.pk }}">
            <button class="btn btn-success">Edit</button>
        </a>
    </td>
    <td>
        <a href="../delete/{{ reservation.pk }}">
            <button class="btn btn-danger">Delete</button>
        </a>
    </td>
</tr>

templates/reservations.html
{% extends 'base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
{{ form.media }}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 mt-5">
            <h1 class="text-center color-main">Reservation</h1>
            <form action="" method="POST" class="color-main">
                {% csrf_token %}
                {% if reserved %}
                    <div class="alert alert-success" role="alert">
                        <ul class="list-unstyled">
                            <li>Your reservervation is {{ reserved }}</li>
                            <li>Under the name: {{ form.name.value }}</li>
                            <li>Email: {{ form.email.value }}</li>
                            <li>Phone: {{ form.phone.value }}</li>
                            <li>Number of persons: {{ form.number_of_persons.value }}</li>
                            <li>Date: {{ form.Date.value }}</li>
                            <li>Time: {{ form.time.value }}</li>
                        </ul>
                    </div>
                {% else %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success px-5">Submit</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/view_reservation.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center color-main mt-5">View Reservations</h1>
<h4 class="text-center color-white">{{ user.username }}</h4>

<div class="container mt-3">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Table for</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for reservation in reservation_list %}
                            {% if user.is_staff %}
                                {% include 'reservation_table.html' %}
                            {% else %}
                                {% if reservation.name == user.username %}
                                    {% include 'reservation_table.html' %}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}